// FOR IMPORTANT GLOBALLY-REFERENCED VARIABLES
AUTH_EXCHANGE_LINK='https://www.strava.com/oauth/authorize?client_id=83199&response_type=code&redirect_uri=http://localhost/exchange_token&approval_prompt=force&scope=activity:read_all'; // This one is how I get the code with which to retrieve the refresh token for my athletes

TIMMY_B_REFRESH_TOKEN = 'ed67f6258bfd8ad0851a4d5c544d0766432ab9e8'; // Done his training, add him back to ATHLETE* arrays once he's back
PAIGE_O_REFRESH_TOKEN = '0726964a5a1735551ccee68f46e7df753b9bebb4';
MARK_M_REFRESH_TOKEN = '23d1f3b6f426daf584d6cce3987fff9b2443ff0c';
DAVID_L_REFRESH_TOKEN = 'e9a8cf64fd7d49df41d5aca427c9dc77a3ed7409';
PATRICK_L_REFRESH_TOKEN = '25a0a96e7a6f57bd393c8e76fc83c68486289790';
MY_REFRESH_TOKEN = 'e62f800366085277ebdb8a54c81a6306f9b01fa9';

// Establishing parallel arrays (update as athletes stop/start new training blocks)
NUM_OF_ACTIVE_GOONS=5;
ATHLETE_NAMES=['ME', 'PATRICK L', 'PAIGE O', 'MARK M', 'DAVID L']; // The list of my current athletes (which can also be found in The Goon Squad)
ATHLETE_TOKENS=[MY_REFRESH_TOKEN, PATRICK_L_REFRESH_TOKEN, PAIGE_O_REFRESH_TOKEN, MARK_M_REFRESH_TOKEN, DAVID_L_REFRESH_TOKEN];

// Essential variables for the sheets
RECAP_STATS_HEADERS_GOONS_RECAP=["ATHLETE", "TALLIED MILEAGE", "TALLIED TIME", "# OF RUNS", "MILEAGE AVG", "TIME AVG", "PACE AVG", "LONG RUN", "LONG RUN DATE"];
RECAP_STATS=["TALLIED MILEAGE", "TALLIED TIME", "# OF RUNS", "MILEAGE AVG", "TIME AVG", "PACE AVG", "LONG RUN", "LONG RUN DATE"];
NUM_OF_RECAP_STATS=RECAP_STATS.length;
ROWS_DOWN_FROM_LAST_RUN_FOR_RECAP_STATS=7;
ROWS_DOWN_FROM_LAST_RUN_FOR_RECAP_STAT_HEADERS=ROWS_DOWN_FROM_LAST_RUN_FOR_RECAP_STATS-1;

WORKOUT_RECAP_STATS_GOONS_RECAP=["ATHLETE", "WKT #", "WKT ID", "RUN",  "DESCRIPTION",	"FULL DATE", "DAY",	"TIME"];
WORKOUT_RECAP_STATS=["WKT #", "WKT ID", "RUN",  "DESCRIPTION",	"FULL DATE", "DAY",	"TIME"];
NUM_OF_WORKOUT_RECAP_STATS=WORKOUT_RECAP_STATS.length;
ROWS_DOWN_FROM_LAST_RUN_FOR_WORKOUT_STATS=ROWS_DOWN_FROM_LAST_RUN_FOR_RECAP_STATS+3;
ROWS_DOWN_FROM_LAST_RUN_FOR_WORKOUT_STATS_HEADERS=ROWS_DOWN_FROM_LAST_RUN_FOR_WORKOUT_STATS-1;

ROW_OF_WEEKLY_RECAP_HEADER_RECAP_SHEET=3;
ROWS_DOWN_FROM_LAST_WEEKLY_RECAP_ROW_HEADER=4;
ROWS_DOWN_FROM_LAST_WEEKLY_RECAP_ROW_STATS=ROWS_DOWN_FROM_LAST_WEEKLY_RECAP_ROW_HEADER+1;

// GOONS SHEET
START_ROW_OF_HEADERS_GOONS_SHEET=1;
START_ROW_OF_ACTIVITIES_GOONS_SHEET=START_ROW_OF_HEADERS_GOONS_SHEET+1;